
export function throwException() {
  throw new Error("Test")
}
